# Generated by Django 5.0 on 2023-12-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_questionstoragegametraining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerstoragegametraining',
            old_name='answer',
            new_name='correct_answers_training',
        ),
        migrations.RemoveField(
            model_name='answerstoragegametraining',
            name='right_answer',
        ),
    ]
