# Generated by Django 5.0 on 2023-12-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_answer_answerstoragegametraining_correct_answers_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerstoragegame',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionstoragegametraining'),
        ),
    ]
