# Generated by Django 5.0 on 2023-12-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_division_userprofile_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserResultsKmbAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
