# Generated by Django 5.0 on 2023-12-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_userresultsaccess_userresultskmbaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('bitrix_user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'responsible_persons',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='game.responsibleperson'),
        ),
    ]
