# Generated by Django 5.0 on 2023-12-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_responsibleperson_userprofile_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertraining',
            name='question',
        ),
    ]
